---
# tasks file for update_package
- name: Check version of package
  shell: dpkg-query -l | grep -q '{{ version }}'  && echo 'Latest' || echo 'Old'
  register: update_status
  changed_when: "update_status.stdout == 'Old'"

- include_tasks: update.yml
  when: "update_status.stdout == 'Old'"

...

