---
- name: Upgrade package to the latest version
  become: true
  apt:
    name: "{{ package }}"
    state: latest
    update_cache: yes
    cache_valid_time: '{{ cache_valid_time }}'
    only_upgrade: yes

- name: Check version of package
  shell: dpkg-query -l | grep -q '{{ version }}'  && echo 'OK' || echo 'Error'
  register: update_status
  changed_when: "update_status == 'Error'"

- debug:
    var: update_status.stdout
...
