---
# tasks file for deploy_apache_web
- block: #====Block for RedHat===
     - name: Install Apache on CentOS servers
       yum : name=httpd status=latest

     - name: Start Apache and enable on boot
       service: name=httpd state=started enabled=yes

  when: ansible_os_family == "RedHat"


- block: #====Block for Debian==== 

     - name: Install Apache Server on Ubuntu servers
       apt : name=apache2 state=latest

     - name: Start Apache and enable on boot
       service: name=apache2 state=started enabled=yes

  when: ansible_os_family == "Debian"


- name: Generate Index.html file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify:
         - Restart Apache on Debian
         - Restart Apache on RedHat

- name: Copy HomePage file to WebServer
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  with_fileglob: "files/*.*"
  
  notify:
         - Restart Apache on Debian
         - Restart Apache on RedHat
