---
 - name: Install Apache Web Server
   hosts: all

   vars:
     source_file: ./MyWebSite/index.html
     destin_file: /var/www/html


   tasks:
   - name: Install Apache Server
     apt : name=apache2 state=latest

   - name: Copy my homepage to servers
     copy: src={{ source_file }} dest={{ destin_file }} mode=0555
     notify: Restart Apache

   - name: Start Apache and enable on boot
     service: name=apache2 state=started enabled=yes
   
   handlers:
   - name: Restart Apache
     service: name=apache2 state=restarted
     
...

