---
 - name: Loops Playbook
   hosts: all
   become: yes


   tasks:
    - name: Say Hello to all
      debug: msg="Hello {{ item }}"
      loop:
       - "Artem"
       - "Alex"
       - "Andrej"
       - "Masha"

    - name: Loop Until example
      shell: echo -n Z >> myfile1.txt && cat myfile1.txt
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find("ZZZZ") == false


    - name: Print Final Output
      debug:
       var: output.stdout       

       #    - name: Install many package
       #      yum: name={{ item }} state=stablled
       #      loop:
       #       - python
       #       - mariadb
       #       - apache2  
