---
- name: My playbook with delegate_to
  hosts: all

  vars: 
   mytext: "Privet"

  tasks: 
  
  - name: Ping test
    ping:

  - name: Unregister server
     shell: echo this server "{{ inventory_hostname }}" was deregistered from our Load Balancer, node name is "{{ ansible_nodename }}" >> /home/log.txt
     delegate_to: 127.0.0.1

     #  - name: Update Database
     #    shell: echo Updating database...
     #    run_once: true 
  
  
  - name: Create file
    copy:
     dest: /home/file1.txt
     content: |
      This is FileN1
      On English Hello
      On Russian {{ mytext }}
     delegate_to: 172.20.90.41


  - name: create file2
    copy: 
     dest: /home/file2.txt
     content: | 
       This is FileN2
       On English Hello
       On Russian {{ mytext }}
   
  - name: Rebbot my servers
    shell: sleep 3 && reboot now
     async: 1
     pool: 0


  - name: wait till my server will come up online
    wait_for: 
     host: "{{ inventory_hostname }}"
     state: started
     delay: 5
     timeout: 40
    delegate_to: 127.0.0.1 
 
