---
- name: My playbook with include
  hosts: all

  vars:
   mytext: "Privet ot Arti!"

  tasks:
  - name: Ping test
    ping:
  

  - name: Create folder
    include: create_folders.yml
   
  - name: Create files
    include: create_files.yml
...    
